"""Initial Migration

Revision ID: 10223aa3d192
Revises: 
Create Date: 2020-07-12 19:17:40.435867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10223aa3d192'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    # ### end Alembic commands ###
